### ISSUE TITLE
Injection Transfuse Activity into Calltrough listener

### ISSUE THREAD

**Issue by ghost** [johncarl81/transfuse#118]
I'd like to inject the matching transfuse activity in my menuController class like this:

``` java
public class MenuController implements ActivityMenuComponent {
    private MenuInflater menuInflater;
    private Context context; // this is of the generated class SearchActivityActivity
    private SearchActivity activity;

    @Inject
    public MenuController(MenuInflater menuInflater, Context context, SearchActivity activity) {
        this.menuInflater = menuInflater;
        this.context = context;
        this.activity = activity;
    }
```

The reason is that I need to call a function I defined in SearchActivity and that is supposed to stay there.

Currently above code yields the following error:

```
Exception in thread "pool-316-thread-1" Exception in thread "pool-316-thread-1" org.androidtransfuse.TransfuseAnalysisException: Unable to find a dependency to proxy
    at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:71)
    at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:41)
    at org.androidtransfuse.gen.variableBuilder.VariableInjectionNodeBuilder.buildInjectionNode(VariableInjectionNodeBuilder.java:41)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:174)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionPoint(InjectionPointFactory.java:84)
    at org.androidtransfuse.analysis.astAnalyzer.InjectionAnalyzer.analyzeType(InjectionAnalyzer.java:55)
    at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:112)
    at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:106)
    at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:85)
    at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:41)
    at org.androidtransfuse.gen.variableBuilder.VariableInjectionNodeBuilder.buildInjectionNode(VariableInjectionNodeBuilder.java:41)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:174)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionPoint(InjectionPointFactory.java:127)
    at org.androidtransfuse.analysis.astAnalyzer.InjectionAnalyzer.analyzeField(InjectionAnalyzer.java:79)
    at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:121)
    at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:106)
    at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:85)
    at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:41)
    at org.androidtransfuse.gen.variableBuilder.VariableInjectionNodeBuilder.buildInjectionNode(VariableInjectionNodeBuilder.java:41)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:174)
    at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
    at org.androidtransfuse.gen.componentBuilder.InjectionNodeFactoryImpl.buildInjectionNode(InjectionNodeFactoryImpl.java:69)
    at org.androidtransfuse.gen.ComponentGenerator.generate(ComponentGenerator.java:78)
    at org.androidtransfuse.gen.AnalysisGeneration.innerRun(AnalysisGeneration.java:47)
    at org.androidtransfuse.gen.AnalysisGeneration.innerRun(AnalysisGeneration.java:29)
    at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
    at org.androidtransfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
    at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
    at org.androidtransfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
    at org.androidtransfuse.transaction.Transaction.run(Transaction.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by knutsoned** [comment]
I just encountered the same issue, and it was difficult to track down the problem since one of the errors points to a generated file for the application class, instead of either the activity or the ActivityMenuCompat-implementing class. I would like to suggest linking to this issue in the Call-Through Events section here to save time for developers in the future: http://androidtransfuse.org/documentation.html#activity

**Comment by johncarl81** [comment]
:+1: @knutsoned, we should add this to the docs (or at least some wording to relfect this).  And, one of the changes for the 0.3.0 needs to be better error reporting.
