### ISSUE TITLE
Debug Logging

### ISSUE THREAD

**Issue by airblaster** [johncarl81/transfuse#119]
Is there some kind of debug logging, so you can trace down the place that causes problems in case of generation errors?

E.g. currently I get the following error and I have no idea what causes it:
```
Exception in thread "pool-40-thread-1" java.lang.NoClassDefFoundError: android/view/ViewGroup
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:259)
	at com.sun.codemodel.JCodeModel.ref(JCodeModel.java:378)
	at com.sun.codemodel.JCodeModel$TypeNameParser.parseTypeName(JCodeModel.java:472)
	at com.sun.codemodel.JCodeModel.parseType(JCodeModel.java:424)
	at org.androidtransfuse.gen.ClassGenerationUtil.type(ClassGenerationUtil.java:68)
	at org.androidtransfuse.gen.variableBuilder.ViewInjectionNodeBuilder.buildInjectionNode(ViewInjectionNodeBuilder.java:61)
	at org.androidtransfuse.gen.variableBuilder.InjectionNodeBuilderSingleAnnotationAdapter.buildInjectionNode(InjectionNodeBuilderSingleAnnotationAdapter.java:42)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:161)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionPoint(InjectionPointFactory.java:127)
	at org.androidtransfuse.analysis.astAnalyzer.InjectionAnalyzer.analyzeField(InjectionAnalyzer.java:79)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:121)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:106)
	at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:85)
	at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:41)
	at org.androidtransfuse.gen.variableBuilder.VariableInjectionNodeBuilder.buildInjectionNode(VariableInjectionNodeBuilder.java:41)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:174)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
	at org.androidtransfuse.gen.componentBuilder.InjectionNodeFactoryImpl.buildInjectionNode(InjectionNodeFactoryImpl.java:69)
	at org.androidtransfuse.gen.ComponentGenerator.generate(ComponentGenerator.java:78)
	at org.androidtransfuse.gen.AnalysisGeneration.innerRun(AnalysisGeneration.java:47)
	at org.androidtransfuse.gen.AnalysisGeneration.innerRun(AnalysisGeneration.java:29)
	at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.androidtransfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.androidtransfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.androidtransfuse.transaction.Transaction.run(Transaction.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Error:java.lang.ClassNotFoundException: android.view.ViewGroup
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
```
Only thing I know this started when I tried to convert a ListView into a Fragment for use in a ViewPager.

**Comment by johncarl81** [comment]
@airblaster, I've added the beginnings of some pretty substantial debug logging using the `-AtransfuseDebugLogging` annotation processor option.  Not sure if this would help with this issue, but it will give more insight into what Transfuse is doing.

**Comment by airblaster** [comment]
Thanks for adding the debug logging.
The project that had above error has unfortunately been stopped due to commercial reasons, so I can't test this anymore.

**Comment by johncarl81** [comment]
Sorry to hear that @airblaster.
