### ISSUE TITLE
Support for loading classes with missing annotations

### ISSUE THREAD

**Issue by Naitbit** [johncarl81/transfuse#153]
Java compiler supports loading classes even if they contain unknown annotations. For example 
```joda-time:joda-time:2.7``` uses annotation ```org.joda.convert.ToString``` from package
```org.joda:joda-convert:1.7``` but does not depend on it.

Currently trying to buildFieldSet with missing annotation causes crash during annotation processing:
```
Exception in thread "pool-2-thread-1" com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.joda.convert.ToString not found
Exception in thread "pool-4-thread-1" org.parceler.transfuse.TransfuseAdapterException: Proxy not initialized prior to use
    at org.parceler.transfuse.adapter.ASTTypeVirtualProxy.getProxy(ASTTypeVirtualProxy.java:45)
    at org.parceler.transfuse.adapter.ASTTypeVirtualProxy.inheritsFrom(ASTTypeVirtualProxy.java:95)
    at org.parceler.transfuse.gen.invocationBuilder.TypeInvocationHelper.coerceType(TypeInvocationHelper.java:60)
    at org.parceler.transfuse.gen.invocationBuilder.PublicInvocationBuilder.buildFieldSet(PublicInvocationBuilder.java:76)
    at org.parceler.transfuse.gen.InvocationBuilder.buildFieldSet(InvocationBuilder.java:71)
    at org.parceler.internal.ReadReferenceVisitor.visit(ReadReferenceVisitor.java:41)
    at org.parceler.internal.ReadReferenceVisitor.visit(ReadReferenceVisitor.java:28)
    at org.parceler.internal.FieldReference.accept(FieldReference.java:41)
    at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:230)
    at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:166)
    at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:100)
    at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:53)
    at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:32)
    at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
    at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
    at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
    at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
    at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Exception in thread "pool-6-thread-1" org.parceler.transfuse.TransfuseAdapterException: Proxy not initialized prior to use
    at org.parceler.transfuse.adapter.ASTTypeVirtualProxy.getProxy(ASTTypeVirtualProxy.java:45)
    at org.parceler.transfuse.adapter.ASTTypeVirtualProxy.inheritsFrom(ASTTypeVirtualProxy.java:95)
    at org.parceler.transfuse.gen.invocationBuilder.TypeInvocationHelper.coerceType(TypeInvocationHelper.java:60)
:app:_compileDebugJava FAILED
    at org.parceler.transfuse.gen.invocationBuilder.PublicInvocationBuilder.buildFieldSet(PublicInvocationBuilder.java:76)
    at org.parceler.transfuse.gen.InvocationBuilder.buildFieldSet(InvocationBuilder.java:71)
    at org.parceler.internal.ReadReferenceVisitor.visit(ReadReferenceVisitor.java:41)
    at org.parceler.internal.ReadReferenceVisitor.visit(ReadReferenceVisitor.java:28)
    at org.parceler.internal.FieldReference.accept(FieldReference.java:41)
    at org.parceler.internal.ParcelableGenerator.buildReadFromParcel(ParcelableGenerator.java:230)
    at org.parceler.internal.ParcelableGenerator.buildParcelRead(ParcelableGenerator.java:166)
    at org.parceler.internal.ParcelableGenerator.generateParcelable(ParcelableGenerator.java:100)
    at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:53)
    at org.parceler.internal.ParcelTransactionWorker.innerRun(ParcelTransactionWorker.java:32)
    at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
    at org.parceler.transfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
    at org.parceler.transfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
    at org.parceler.transfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
    at org.parceler.transfuse.transaction.Transaction.run(Transaction.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Issue can be reproduced by trying to Parcel DateTime (from joda package)
```groovy
compile 'joda-time:joda-time:2.7'
compile 'org.parceler:parceler-api:0.2.16'
provided 'org.parceler:parceler:0.2.16'
```

```java
package com.byoutline.example;

import com.byoutline.example.DateTimeParcelConverter;

import org.joda.time.DateTime;
import org.parceler.Parcel;
import org.parceler.ParcelPropertyConverter;

@Parcel(Parcel.Serialization.FIELD)
public class ProjectExample {

    @ParcelPropertyConverter(DateTimeParcelConverter.class)
    public DateTime launchedAt;
}
```
```java
package com.byoutline.example;

import android.os.Parcel;

import org.joda.time.DateTime;
import org.parceler.converter.NullableParcelConverter;

public class DateTimeParcelConverter extends NullableParcelConverter<DateTime> {

    @Override
    public void nullSafeToParcel(DateTime input, Parcel parcel) {
        parcel.writeLong(input.getMillis());
    }

    @Override
    public DateTime nullSafeFromParcel(Parcel parcel) {
        return new DateTime(parcel.readLong());
    }
}
```

This annotation did cause problems for other projects like Scala: https://stackoverflow.com/questions/23660990/how-is-scalaruntime-stringofx-not-failing-when-x-tostring-fails
but since they managed to fix it and ToString annotation is not needed for this serialization it may be possible to support it.

**Comment by johncarl81** [comment]
@Naitbit, sorry for the delay in answering this issue... seems that it fell through the cracks.  I think the referenced PR fixes this issue and will be applied to Parceler in the next release.
