### ISSUE TITLE
Activity/Fragment lifecycle calls to super not enforced

### ISSUE THREAD

**Issue by justincpollard** [johncarl81/transfuse#179]
In the Android framework code, both `Activity` and `Fragment` enforce calls to super lifecycle methods. For example:

```java
class ExampleFragment extends Fragment {

   @Override
   public void onResume(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);// This call is enforced by the framework
      ...
   }
}
```

However, when using inheritance in Android Transfuse, super calls are not enforced in `@Fragment` and `@Activity` annotated classes. This can cause (difficult to discover) bugs when both a parent and child class implement `@OnCreate` (or `@OnResume`, `@OnPause`, etc).

Is it possible for Transfuse to throw an error if this contract is not honored?

**Comment by johncarl81** [comment]
@justincpollard, is this the case for Transfuse to error?:

```java
class ExampleFragment extends Fragment {
   @Override
   public void onResume(Bundle savedInstanceState) {
      //no super call
   }
}
```

**Comment by justincpollard** [comment]
Well, sort of. Let me try to explain further. In our project, we have the need to contain `Fragment` functionality that's used in a few different places in parent classes. For example:

```java
class ParentComponent {
    @OnCreate
    public void onCreate(Bundle savedState) {
        // Essential onCreate code here
    }
}
```

We will then extend the parent class in an @Fragment annotated class:

```java
@Fragment(type = MyFragment.class)
@Layout(R.layout.child_fragment)
class ChildComponent extends ParentComponent {
   @OnCreate
    public void onCreate(Bundle savedState) {
        // This is where the framework would require a call to 
        //super.onCreate(), but Transfuse does not
    }
}
```

In this case, the generated `ChildComponentFragment` will only call through to `ChildComponent.onCreate()`. This would be fine except that the author of `ChildComponent` forgot to call `super.onCreate()`, thus missing out on the essential code in the `ParentComponent`.

The framework helps engineers avoid this mistake by enforcing calls to `super.onCreate()` in child fragments, whether they extend a framework fragment or an extending fragment. To do this, Android throws an exception at runtime that looks like this:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.appcompat21test/com.test.appcompat21test.MainActivity}: android.view.InflateException: Binary XML file line #1: Error inflating class fragment
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class fragment
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.test.appcompat21test.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.support.v4.app.SuperNotCalledException: Fragment MainActivityFragment2{282550a8 #0 id=0x7f0a0050} did not call through to super.onCreate()
            at android.support.v4.app.Fragment.performCreate(Fragment.java:1768)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:917)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1116)
            at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1218)
            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2170)
            at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:300)
            at android.support.v7.app.AppCompatDelegateImplV7.callActivityOnCreateView(AppCompatDelegateImplV7.java:838)
            at android.support.v7.app.AppCompatDelegateImplV11.callActivityOnCreateView(AppCompatDelegateImplV11.java:34)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:826)
            at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.test.appcompat21test.MainActivity.onCreate(MainActivity.java:14)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

What I'm requesting is that Transfuse throws a warning/build error if an @Fragment annotated class overrides a lifecycle method, but does not call super.

**Comment by johncarl81** [comment]
My gut is telling me no on this one.  Here's what I'm thinking...

One key underlying feature of Transfuse is the ability to cancel or supersede functionality in an overridden class.  This is a requirement of JSR330 and happens in the core injection engine.  Basically, this means that you can avoid an injection or change what specific injection is made (maybe introduce a different qualifier) by overriding a method call.  This should be consistent across the entire library and I think it should definitely apply to the lifecycle events.

With Transfuse I've tried to get away from some of the crufty patterns of Android.  Certainly requiring the super call is one of them.

Is your super call only required via the `onCreate()`?  If so, you could leverage the constructor to perform the same task and would enforce that the super constructor is called:

```java
class Super {
    public Super(String requiredParam) {
        //..code that needs to be called
    }
}

@Fragment
class Base extends Super {
    public Base() {
        super.("I cant not call this constructor");
    }
}
```

Also, if your base class requires a call and the order of the calls isn't important you could name your event methods so they don't override each other.  Both will be called:

```java
class Super {
    @OnCreate public superImportantCall() {}
}

@Fragment
class Base extends Super {
    @OnCreate public notOverridden() {}
}
```

There may be an opportunity here for anther annotation processor to take the reins.  I could see the following api working:

```java
class Super {
    @OverrideSuperCallAssert
    public someMethod(String requiredParam) {
        //..code that needs to be called
    }
}

class Base extends Super {
    public someMethod(String requiredParam) {
        //
    }
}
```

This would require that each class is analyzed during compilation to look for overridden methods.  If the overridden method is annotated with the given annotation `@OverrideSuperCallAssert` then the annotation processor would leverage the [Trees api](http://docs.oracle.com/javase/7/docs/jdk/api/javac/tree/com/sun/source/util/Trees.html) to see if there is a super call made during the method execution.  Honestly, this sounds pretty cool and I think I'd like to try my hand at getting this to work.

So, maybe my answer is:  This is a cool idea, lets do it in a new project!  As always, I'd love to collaborate if you're interested @justincpollard.

**Comment by justincpollard** [comment]
I used onCreate as an example, but we've used this pattern in other lifecycle methods as well. Changing the method name is certainly a way to execute both code paths, but is still subject to human error.

I think the @OverrideSuperCallAssert solution would work here nicely! Is there a reason you think this annotation doesn't belong in Transfuse?

**Comment by johncarl81** [comment]
We could also introduce a `@ShouldNotOverride` annotation to help avoid that human error ;-).  I guess you could make the method `final` in that case though.

I guess I see this applying to more than Transfuse components and could dovetail into Transfuse nicely or be used on its own in plain olde Java.

**Comment by justincpollard** [comment]
What if you incorporated functionality into the lifecycle annotations that warned the programmer of these potential mistakes?

**Comment by justincpollard** [comment]
I guess my last comment is essentially what I was first asking for ... ;-) Still, if that were possible, it might fit into the scope of transfuse nicely, and would maintain one of the beneficial features of using the framework components.

**Comment by johncarl81** [comment]
Reread this... I'm not sold this should be a requirement of lifecycle events.  I think that there is value in being able to override and cancel a super classes' functionality (ie: not require a super method call).

I think there are a few options available to you to make sure your super classes' code is called... In 
particular I like making the required event method `final`.

Am I not understanding your issue 100%?  Am I missing a key fact of event methods that you have seen that I am not thinking about?

**Comment by justincpollard** [comment]
My thinking is that lifecycle events perform build up and tear down functionality which should be performed by child classes as well. If you agree with that, then there doesn't seem to be a need for canceling a parent lifecycle event's functionality; in fact it could be harmful (cause memory leaks, leave text fields un populated, etc). If a child class does want to cancel lifecycle functionality, my hunch is that it shouldn't inherit from that parent. 

I also like to adhere to the conventions that 1) only one method per class should be annotated with @OnCreate (and other lifecycle annotations), and 2) the name of the method should mirror its annotation (e.g. @OnCreate should be called `public void onCreate()` or `public void onCreate(Bundle savedState)`. These are artificial restraints that I've placed in my code, but I think they prove useful from an organization/ease of understanding perspective.

**Comment by johncarl81** [comment]
I'm really curious that you guys went this direction... what benefit does extending your base class have over composing the base class within the sub class?  ie:

```java
class Sub {
    @Inject Base base;
    @OnCreate public void onCreate(){
        //...
    }
}
```
vs
```java
class Sub extends Base {
     @OnCreate public void onCreate(){
        super.onCreate();
        //...
    }
}
```
With Base:
```java
class Base {
    @OnCreate public void onCreate(){}
}
```

**Comment by justincpollard** [comment]
In retrospect, that might have been a better decision. We may still go that way, but it's sometimes tough to get time to refactor code when you've got features to build ;-)

Still, does injecting the `Base` cause the base to undergo the same lifecycle as the containing fragment? If not, the developer still needs to remember to call `base.onCreateDelegate()`, `base.onResumeDelegate()`, etc.

**Comment by johncarl81** [comment]
I totally understand and I'm really not faulting you for it.

Yes, anything injected by Transfuse is able to receive the lifecycle events.  Really the root annotated component is no different than any other injected class instance.  It's designed so you can inject multiple distinct instances that would react to the lifecycle... so you could reuse and compose your application out of smaller, more maintainable parts:
```java
@Activity
class Example {
    @Inject GoogleAnalyticsTracker tracker;
    @Inject GooglePlusLogin loginHandler;
    @Inject FacebookLoginCallback facebookCallback;
}
```

As you can imagine I'm a big fan of "Favor composition over inheritance" (#14 from Effective Java) but I'm always looking for instance where it doesn't fit or where I've overreached.

**Comment by justincpollard** [comment]
Cool, I wasn't aware that injected components would receive lifecycle events. Since that's the case, we'll need to spend some time refactoring, I think :-) Thanks for your help on this, John!

**Comment by johncarl81** [comment]
Thanks for the stimulating discussion @justincpollard.  Let me know if I can help!
