### ISSUE TITLE
problem building with android-apt:1.6

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/transfuse#182]
```
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:45)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:101)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:34)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:157)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:137)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:91)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:243)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:230)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at org.androidtransfuse.sun.codemodel.JCodeModel.ref(JCodeModel.java:378)
	at org.androidtransfuse.sun.codemodel.JCodeModel$TypeNameParser.parseTypeName(JCodeModel.java:472)
	at org.androidtransfuse.sun.codemodel.JCodeModel.parseType(JCodeModel.java:424)
	at org.androidtransfuse.gen.ClassGenerationUtil.type(ClassGenerationUtil.java:69)
	at org.androidtransfuse.gen.variableBuilder.FragmentViewInjectionNodeBuilder.buildInjectionNode(FragmentViewInjectionNodeBuilder.java:62)
	at org.androidtransfuse.gen.variableBuilder.InjectionNodeBuilderSingleAnnotationAdapter.buildInjectionNode(InjectionNodeBuilderSingleAnnotationAdapter.java:43)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:161)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionPoint(InjectionPointFactory.java:127)
	at org.androidtransfuse.analysis.astAnalyzer.InjectionAnalyzer.analyzeField(InjectionAnalyzer.java:79)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:126)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:145)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:110)
	at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:89)
	at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:45)
	at org.androidtransfuse.gen.variableBuilder.VariableInjectionNodeBuilder.buildInjectionNode(VariableInjectionNodeBuilder.java:42)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:174)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:138)
	at org.androidtransfuse.experiment.generators.OnCreateInjectionGenerator$1.generate(OnCreateInjectionGenerator.java:91)
	at org.androidtransfuse.experiment.ComponentBuilder$MethodMetaData.build(ComponentBuilder.java:73)
	at org.androidtransfuse.experiment.ComponentBuilder.build(ComponentBuilder.java:118)
	at org.androidtransfuse.experiment.ComponentGenerator.build(ComponentGenerator.java:51)
	at org.androidtransfuse.gen.AnalysisGeneration.innerRun(AnalysisGeneration.java:47)
	at org.androidtransfuse.gen.AnalysisGeneration.innerRun(AnalysisGeneration.java:29)
	at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.androidtransfuse.transaction.CodeGenerationScopedTransactionWorker.innerRun(CodeGenerationScopedTransactionWorker.java:47)
	at org.androidtransfuse.transaction.AbstractCompletionTransactionWorker.run(AbstractCompletionTransactionWorker.java:35)
	at org.androidtransfuse.transaction.ScopedTransactionWorker.run(ScopedTransactionWorker.java:55)
	at org.androidtransfuse.transaction.Transaction.run(Transaction.java:77)
	at org.androidtransfuse.guava.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at org.androidtransfuse.transaction.TransactionProcessorPool.execute(TransactionProcessorPool.java:60)
	at org.androidtransfuse.transaction.TransactionProcessorComposite.execute(TransactionProcessorComposite.java:37)
	at org.androidtransfuse.transaction.TransactionProcessorChannel.execute(TransactionProcessorChannel.java:43)
	at org.androidtransfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:38)
	at org.androidtransfuse.transaction.TransactionProcessorComposite.execute(TransactionProcessorComposite.java:37)
	at org.androidtransfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:38)
	at org.androidtransfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:41)
	at org.androidtransfuse.transaction.TransactionProcessorChain.execute(TransactionProcessorChain.java:41)
	at org.androidtransfuse.processor.TransfuseProcessor.execute(TransfuseProcessor.java:66)
	at org.androidtransfuse.TransfuseAnnotationProcessor.process(TransfuseAnnotationProcessor.java:159)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 33 more
Caused by: java.lang.RuntimeException: Stub!
	at android.graphics.Color.argb(Color.java:10)
	at com.yahoo.mobile.client.android.util.rangeseekbar.RangeSeekBar.<clinit>(RangeSeekBar.java:60)
	... 82 more

```

**Comment by dbachelder** [comment]
this works on 1.5.1 with no changes.

**Comment by johncarl81** [comment]
Hmm, here's the relevant line in CodeModel:
```java
    public JClass ref(String fullyQualifiedClassName) {
        try {
            // try the context class loader first
            return ref(SecureLoader.getContextClassLoader().loadClass(fullyQualifiedClassName));
        } catch (ClassNotFoundException e) {
            // fall through
        }
        // then the default mechanism.
        try {
            return ref(Class.forName(fullyQualifiedClassName)); // Line 378
        } catch (ClassNotFoundException e1) {
            // fall through
        }

        // assume it's not visible to us.
        return new JDirectClass(this,fullyQualifiedClassName);
    }
```
Which is returning a class instance for the given class name (presumably the `RangeSeekBar`.  In turn, referencing the class initializes the static variables, hence: `<clinit>`.  This then calls the `Color.argb()` method, which is stubbed out in the Java Android API.

Worth noting, if the given class is not found (Class.forName() throws an exception), then a `JDirectClass` is used as a fall-through, which only references the Android class by name, and not by Class.

Did android-apt change between 1.5 and 1.6 to either put the Android library on the classpath during annotation processing or did something else change?

@hvisser, would you mind lending your expertise here?

**Comment by johncarl81** [comment]
BTW, I just confirmed the issue.. injecting RangeSeekBar worked with android-apt 1.5.1, but failed with 1.6

**Comment by johncarl81** [comment]
Doing some tests, RangeSeekBar is not on the classpath during an annotation processing pass in 1.5.1 but it is on the classpath with 1.6

**Comment by johncarl81** [comment]
I think this error stems from the way CodeModel works... it tries to eagerly fetch a class by class name.  #183

**Comment by hvisser** [comment]
There has been a change to the plugin in this area so that the processor path would better match the class path (e.g without using android-apt). So I'd guess this would also happen without `android-apt`?

**Comment by johncarl81** [comment]
Yes, changing the scope of these to `provided` results in the same error.  Thanks for the input @hvisser.

@dbachelder, could you review the PR fix?
