### ISSUE TITLE
IntentService with Intent Extras

### ISSUE THREAD

**Issue by dbachelder** [johncarl81/transfuse#90]
So I've got a service with an Extra annotation... 

`@Extra(value = "id", optional = false) String id`

but it doesn't want to generate the strategy the same way it does with activities... is this an relatively easy change?

```
org.androidtransfuse.TransfuseAnalysisException: Unable to find injection node for annotated type: java.lang.String@org.androidtransfuse.annotations.Extra(optional=false,value=id)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:165)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionNode(InjectionPointFactory.java:153)
	at org.androidtransfuse.analysis.InjectionPointFactory.buildInjectionPoint(InjectionPointFactory.java:84)
	at org.androidtransfuse.analysis.astAnalyzer.InjectionAnalyzer.analyzeType(InjectionAnalyzer.java:55)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:112)
	at org.androidtransfuse.analysis.Analyzer.scanClassHierarchy(Analyzer.java:106)
	at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:85)
	at org.androidtransfuse.analysis.Analyzer.analyze(Analyzer.java:41)
	at org.androidtransfuse.gen.variableBuilder.VariableInjectionNodeBuilder.buildInjectionNode(VariableInjectionNodeBuilder.java:41)
```

**Comment by johncarl81** [comment]
I believe this is implemented with the latest IntentFactory work... reopen if this doesn't work.
